In [1]:
import pandas as pd
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [2]:



pit_agrs_100_30k = pd.read_csv('../cass_exp/pit_40_mcts/pit40_mcts_agrs_100.csv', header = 2)

pit_agrs_100_30k.sort_values(by='step', inplace=True)

step_sums = dict() 
# {key: (reward_sum, count, length_of_run) }

for index, row, in pit_agrs_100_30k.iterrows():
    step = row['step']
    if step in step_sums:
        # adding rewards for the step
        step_sums[step][0] += row['run/total_reward']
        step_sums[step][1] += 1
        step_sums[step][2] += row['run/length']
    else:
        step_sums[step] = [0, 1, row['run/length']]
        step_sums[step][0] += row['run/total_reward']
        

# take average reward and length at each saved step
df_av_at_step = pd.DataFrame(columns=['step', 'reward', 'length'])


for key, value in step_sums.items():
    
    mean_reward = value[0] / value[1]
    mean_length = value[2] / value[1]
    
    
    df_av_at_step = df_av_at_step.append({'step': key, 'reward': mean_reward, 'length': mean_length}, ignore_index=True)
df_av_at_step.set_index('step')


rolling = df_av_at_step.ewm(adjust = True, span=1000).mean()
rolling_se = df_av_at_step.ewm(adjust = True, span = 1000).var()
rolling

df_av_at_step['reward'] = rolling['reward']
df_av_at_step['reward_se'] = rolling_se['reward']
df_av_at_step['length_se'] = rolling_se['length']
df_av_at_step['length'] = rolling['length']

df_av_at_step = df_av_at_step.fillna(0);df_av_at_step
df_agrs_40 = df_av_at_step
df_agrs_40

          step    reward     length  reward_se   length_se
0          0.0  0.070000  95.010000   0.000000    0.000000
1         22.0  0.034965  97.507495   0.002450   12.450050
2         24.0  0.023287  98.339992   0.001632    8.291731
3         26.0  0.017448  98.756240   0.001223    6.212575
4         29.0  0.013944  99.005988   0.000977    4.965085
...        ...       ...        ...        ...         ...
21299  29995.0  0.819853  43.388290   0.095036  511.512101
21300  29996.0  0.820213  43.373028   0.094911  510.606553
21301  29997.0  0.820572  43.362293   0.094786  509.643983
21302  29999.0  0.820930  43.353577   0.094661  508.663697
21303  30000.0  0.819290  43.466757   0.095817  514.052204

[21304 rows x 5 columns]

In [3]:



pit_agrs_100_30k = pd.read_csv('../cass_exp/pit_40_mcts/pit40_mcts_no_agrs_100.csv', header = 2)

pit_agrs_100_30k.sort_values(by='step', inplace=True)

step_sums = dict() 
# {key: (reward_sum, count, length_of_run) }

for index, row, in pit_agrs_100_30k.iterrows():
    step = row['step']
    if step in step_sums:
        # adding rewards for the step
        step_sums[step][0] += row['run/total_reward']
        step_sums[step][1] += 1
        step_sums[step][2] += row['run/length']
    else:
        step_sums[step] = [0, 1, row['run/length']]
        step_sums[step][0] += row['run/total_reward']
        

# take average reward and length at each saved step
df_av_at_step = pd.DataFrame(columns=['step', 'reward', 'length'])


for key, value in step_sums.items():
    
    mean_reward = value[0] / value[1]
    mean_length = value[2] / value[1]
    
    
    df_av_at_step = df_av_at_step.append({'step': key, 'reward': mean_reward, 'length': mean_length}, ignore_index=True)
df_av_at_step.set_index('step')


rolling = df_av_at_step.ewm(adjust = True, span=1000).mean()
rolling_se = df_av_at_step.ewm(adjust = True, span = 1000).var()
rolling

df_av_at_step['reward'] = rolling['reward']
df_av_at_step['reward_se'] = rolling_se['reward']
df_av_at_step['length_se'] = rolling_se['length']
df_av_at_step['length'] = rolling['length']

df_av_at_step = df_av_at_step.fillna(0);df_av_at_step
df_no_agrs_40 = df_av_at_step
df_no_agrs_40

          step    reward     length  reward_se   length_se
0          0.0  0.080000  94.610000   0.000000    0.000000
1         22.0  0.039960  97.307695   0.003200   14.526050
2         24.0  0.026613  98.206925   0.002131    9.674346
3         26.0  0.019940  98.656540   0.001597    7.248499
4         27.0  0.015936  98.926308   0.001276    5.792995
...        ...       ...        ...        ...         ...
26603  29996.0  0.857575  41.847268   0.049481  267.231438
26604  29997.0  0.857460  41.863557   0.049389  266.830178
26605  29998.0  0.857745  41.843850   0.049331  266.491242
26606  29999.0  0.858029  41.824848   0.049272  266.139330
26607  30000.0  0.856362  41.937371   0.050563  271.938352

[26608 rows x 5 columns]

In [4]:



pit_agrs_100_30k = pd.read_csv('../cass_exp/pit_20_mcts/pit20_agrs_merge_100.csv', header = 2)

pit_agrs_100_30k.sort_values(by='step', inplace=True)

step_sums = dict() 
# {key: (reward_sum, count, length_of_run) }

for index, row, in pit_agrs_100_30k.iterrows():
    step = row['step']
    if step in step_sums:
        # adding rewards for the step
        step_sums[step][0] += row['run/total_reward']
        step_sums[step][1] += 1
        step_sums[step][2] += row['run/length']
    else:
        step_sums[step] = [0, 1, row['run/length']]
        step_sums[step][0] += row['run/total_reward']
        

# take average reward and length at each saved step
df_av_at_step = pd.DataFrame(columns=['step', 'reward', 'length'])


for key, value in step_sums.items():
    
    mean_reward = value[0] / value[1]
    mean_length = value[2] / value[1]
    
    
    df_av_at_step = df_av_at_step.append({'step': key, 'reward': mean_reward, 'length': mean_length}, ignore_index=True)
df_av_at_step.set_index('step')


rolling = df_av_at_step.ewm(adjust = True, span=1000).mean()
rolling_se = df_av_at_step.ewm(adjust = True, span = 1000).var()
rolling

df_av_at_step['reward'] = rolling['reward']
df_av_at_step['reward_se'] = rolling_se['reward']
df_av_at_step['length_se'] = rolling_se['length']
df_av_at_step['length'] = rolling['length']

df_av_at_step = df_av_at_step.fillna(0);df_av_at_step
df_agrs_20 = df_av_at_step
df_agrs_20

          step    reward     length  reward_se   length_se
0          0.0  0.020000  98.850000   0.000000    0.000000
1         41.0  0.009990  99.425575   0.000200    0.661250
2         44.0  0.006653  99.617433   0.000133    0.440392
3        100.0  0.007544  99.600780   0.000092    0.294406
4        141.0  0.006029  99.680944   0.000080    0.252555
...        ...       ...        ...        ...         ...
13648  29996.0  0.734917  52.681104   0.148642  739.660845
13649  29997.0  0.733448  52.775647   0.149423  742.652214
13650  29998.0  0.733981  52.728143   0.149266  742.296698
13651  29999.0  0.734513  52.670745   0.149109  742.460904
13652  30000.0  0.733184  52.757409   0.149693  744.732865

[13653 rows x 5 columns]

In [ ]:



pit_agrs_100_30k = pd.read_csv('../cass_exp/pit_20_mcts/pit20_no_agrs_merge_100.csv', header = 2)

pit_agrs_100_30k.sort_values(by='step', inplace=True)

step_sums = dict() 
# {key: (reward_sum, count, length_of_run) }

for index, row, in pit_agrs_100_30k.iterrows():
    step = row['step']
    if step in step_sums:
        # adding rewards for the step
        step_sums[step][0] += row['run/total_reward']
        step_sums[step][1] += 1
        step_sums[step][2] += row['run/length']
    else:
        step_sums[step] = [0, 1, row['run/length']]
        step_sums[step][0] += row['run/total_reward']
        

# take average reward and length at each saved step
df_av_at_step = pd.DataFrame(columns=['step', 'reward', 'length'])


for key, value in step_sums.items():
    
    mean_reward = value[0] / value[1]
    mean_length = value[2] / value[1]
    
    
    df_av_at_step = df_av_at_step.append({'step': key, 'reward': mean_reward, 'length': mean_length}, ignore_index=True)
df_av_at_step.set_index('step')


rolling = df_av_at_step.ewm(adjust = True, span=1000).mean()
rolling_se = df_av_at_step.ewm(adjust = True, span = 1000).var()
rolling

df_av_at_step['reward'] = rolling['reward']
df_av_at_step['reward_se'] = rolling_se['reward']
df_av_at_step['length_se'] = rolling_se['length']
df_av_at_step['length'] = rolling['length']

df_av_at_step = df_av_at_step.fillna(0);df_av_at_step
df_no_agrs_20 = df_av_at_step
df_no_agrs_20

In [ ]:


pit_agrs_100_30k = pd.read_csv('../cass_exp/pit_100_each/pit_agrs_100_30k_merge.csv', header = 3)

pit_agrs_100_30k.sort_values(by='step', inplace=True)

step_sums = dict() 
# {key: (reward_sum, count, length_of_run) }

for index, row, in pit_agrs_100_30k.iterrows():
    step = row['step']
    if step in step_sums:
        # adding rewards for the step
        step_sums[step][0] += row['run/total_reward']
        step_sums[step][1] += 1
        step_sums[step][2] += row['run/length']
    else:
        step_sums[step] = [0, 1, row['run/length']]
        step_sums[step][0] += row['run/total_reward']
        

# take average reward and length at each saved step
df_av_at_step = pd.DataFrame(columns=['step', 'reward', 'length'])


for key, value in step_sums.items():
    
    mean_reward = value[0] / value[1]
    mean_length = value[2] / value[1]
    
    
    df_av_at_step = df_av_at_step.append({'step': key, 'reward': mean_reward, 'length': mean_length}, ignore_index=True)
df_av_at_step.set_index('step')


rolling = df_av_at_step.ewm(adjust = True, span=1000).mean()
rolling_se = df_av_at_step.ewm(adjust = True, span = 1000).var()
rolling

df_av_at_step['reward'] = rolling['reward']
df_av_at_step['reward_se'] = rolling_se['reward']
df_av_at_step['length_se'] = rolling_se['length']
df_av_at_step['length'] = rolling['length']

df_av_at_step = df_av_at_step.fillna(0);df_av_at_step
df_agrs = df_av_at_step
df_agrs

In [ ]:
pit_no_agrs_100_30k = pd.read_csv('../cass_exp/pit_100_each/pit_no_agrs_100_30k_merge.csv', header = 2)

pit_no_agrs_100_30k.sort_values(by='step', inplace=True)

#PIPELINE FOR AVERAGE OF MOVING AVERAGES

step_sums = dict() 
# {key: (reward_sum, count, length_of_run) }

for index, row, in pit_no_agrs_100_30k.iterrows():
    step = row['step']
    if step in step_sums:
        # adding rewards for the step
        step_sums[step][0] += row['run/total_reward']
        step_sums[step][1] += 1
        step_sums[step][2] += row['run/length']
    else:
        step_sums[step] = [0, 1, row['run/length']]
        step_sums[step][0] += row['run/total_reward']
        
# take average reward and length at each saved step
df_av_at_step = pd.DataFrame(columns=['step', 'reward', 'length']);df_av_at_step

for key, value in step_sums.items():
    
    mean_reward = value[0] / value[1]
    mean_length = value[2] / value[1]
    
    
    df_av_at_step = df_av_at_step.append({'step': key, 'reward': mean_reward, 'length': mean_length}, ignore_index=True)

df_av_at_step.set_index('step')

rolling = df_av_at_step.ewm(adjust = True, span=1000).mean()
rolling_se = df_av_at_step.ewm(adjust = True, span=1000).var()
df_av_at_step['reward'] = rolling['reward']
df_av_at_step['reward_se'] = rolling_se['reward']
df_av_at_step['length_se'] = rolling_se['length']
df_av_at_step['length'] = rolling['length']


df_av_at_step = df_av_at_step.fillna(0);df_av_at_step
df_no_agrs = df_av_at_step
df_no_agrs

In [ ]:
fig, axs = plt.subplots(ncols=1)
plt.title('Pit 100 * 30k steps at 80 expansions')
sns.lineplot(x="step", y="reward", data=df_agrs,ax=axs, ci=99)
sns.lineplot(x="step", y="reward", data=df_no_agrs,ax=axs, ci=99)


axs.fill_between(x=df_agrs["step"], y1=df_agrs["reward"] + df_agrs["reward_se"], 
                 y2=df_agrs["reward"] - df_agrs["reward_se"], alpha=.5)
axs.fill_between(x=df_no_agrs["step"], y1=df_no_agrs["reward"] + df_no_agrs["reward_se"], 
                 y2=df_no_agrs["reward"] - df_no_agrs["reward_se"], alpha=.5)



axs.legend(['agrs','vanilla'], loc=4)

In [ ]:
fig, axs = plt.subplots(ncols=1)
plt.title('Pit 100 * 30k steps at 40 expansions')
sns.lineplot(x="step", y="reward", data=df_agrs_40,ax=axs, ci=99)
sns.lineplot(x="step", y="reward", data=df_no_agrs_40,ax=axs, ci=99)


axs.fill_between(x=df_agrs_40["step"], y1=df_agrs_40["reward"] + df_agrs_40["reward_se"], 
                 y2=df_agrs_40["reward"] - df_agrs_40["reward_se"], alpha=.5)
axs.fill_between(x=df_no_agrs_40["step"], y1=df_no_agrs_40["reward"] + df_no_agrs_40["reward_se"], 
                 y2=df_no_agrs_40["reward"] - df_no_agrs_40["reward_se"], alpha=.5)



axs.legend(['agrs','vanilla'], loc=4)

In [ ]:
fig, axs = plt.subplots(ncols=1)
plt.title('Pit 100 * 30k steps at 20 expansions')
sns.lineplot(x="step", y="reward", data=df_agrs_20,ax=axs, ci=99)
sns.lineplot(x="step", y="reward", data=df_no_agrs_20,ax=axs, ci=99)


axs.fill_between(x=df_agrs_20["step"], y1=df_agrs_20["reward"] + df_agrs_20["reward_se"], 
                 y2=df_agrs_20["reward"] - df_agrs_20["reward_se"], alpha=.5)
axs.fill_between(x=df_no_agrs_20["step"], y1=df_no_agrs_20["reward"] + df_no_agrs_20["reward_se"], 
                 y2=df_no_agrs_20["reward"] - df_no_agrs_20["reward_se"], alpha=.5)



axs.legend(['agrs','vanilla'], loc=4)

In [ ]:
fig, axs = plt.subplots(ncols=1)
plt.title('Pit 100 * 30k steps at 20 expansions')

sns.lineplot(x="step", y="reward", data=df_agrs,ax=axs, ci=99)
sns.lineplot(x="step", y="reward", data=df_no_agrs,ax=axs, ci=99)


axs.fill_between(x=df_agrs["step"], y1=df_agrs["reward"] + df_agrs["reward_se"], 
                 y2=df_agrs["reward"] - df_agrs["reward_se"], alpha=.5)
axs.fill_between(x=df_no_agrs["step"], y1=df_no_agrs["reward"] + df_no_agrs["reward_se"], 
                 y2=df_no_agrs["reward"] - df_no_agrs["reward_se"], alpha=.5)


sns.lineplot(x="step", y="reward", data=df_agrs_40,ax=axs, ci=99)
sns.lineplot(x="step", y="reward", data=df_no_agrs_40,ax=axs, ci=99)


axs.fill_between(x=df_agrs_40["step"], y1=df_agrs_40["reward"] + df_agrs_40["reward_se"], 
                 y2=df_agrs_40["reward"] - df_agrs_40["reward_se"], alpha=.5)
axs.fill_between(x=df_no_agrs_40["step"], y1=df_no_agrs_40["reward"] + df_no_agrs_40["reward_se"], 
                 y2=df_no_agrs_40["reward"] - df_no_agrs_40["reward_se"], alpha=.5)




sns.lineplot(x="step", y="reward", data=df_agrs_20,ax=axs, ci=99)
sns.lineplot(x="step", y="reward", data=df_no_agrs_20,ax=axs, ci=99)


axs.fill_between(x=df_agrs_20["step"], y1=df_agrs_20["reward"] + df_agrs_20["reward_se"], 
                 y2=df_agrs_20["reward"] - df_agrs_20["reward_se"], alpha=.5)
axs.fill_between(x=df_no_agrs_20["step"], y1=df_no_agrs_20["reward"] + df_no_agrs_20["reward_se"], 
                 y2=df_no_agrs_20["reward"] - df_no_agrs_20["reward_se"], alpha=.5)



axs.legend(['agrs80','van80', 'agrs40', 'van40', 'agrs20', 'van20' ], loc=4)